Checking the CIDnetworks Suite: Covariates
========================================================

A.C. Thomas, November 22

 `r library(CIDnetworks)`

Here we test the fitting and plotting options for 

Component alone, three covariates.

```{r echo=FALSE}
n.nodes <- 100; covs <- 3
test.cov <- COV(n.nodes=100, covariates=matrix(rbinom(covs*n.nodes*(n.nodes-1)/2, 1, 0.5), ncol=3), coef.cov=1:covs, generate=TRUE)
test.cov.pieces <- test.cov$pieces()
test.cov.value <- test.cov$value()

test.cov.gibbs <- test.cov$gibbs.full(draws=500, report=100, burnin=200, thin=2, make.random.start=TRUE)
test.cov$gibbs.plot(test.cov.gibbs)

test.cov.gibbs.unlist <- list.output.to.matrices (test.cov.gibbs)

test.cov.gibbs.value <- test.cov$gibbs.value(test.cov.gibbs)
plot(test.cov.gibbs.unlist$log.lik, main="Log-likelihood")
plot(test.cov.gibbs.unlist$coef.cov[1,], main=paste("Coefficient 1", test.cov.pieces$coef.cov[1])); abline(h=test.cov.pieces$coef.cov[1], lwd=3, col=2)
netplot(test.cov$edge.list, test.cov.value, colvalues=20, main="Oracle values")
netplot(test.cov$edge.list, apply(test.cov.gibbs.value, 1, mean), colvalues=20, main="Fitted values")
plot(test.cov.value, apply(test.cov.gibbs.value, 1, mean))
```

Gaussian within CID:

```{r}
test.cov.g <- CID.generate (100, components=list(COV(covariates=matrix(rbinom(covs*n.nodes*(n.nodes-1)/2, 1, 0.5), ncol=3), coef.cov=1:covs)), intercept=1, residual.variance=2, generate=TRUE, class="gaussian")
test.cov.g.pieces <- test.cov.g$pieces()
test.cov.g.value <- test.cov.g$value()

test.cov.g.gibbs <- test.cov.g$gibbs.full(draws=300, report=100, burnin=300, make.random.start=TRUE)
tcggs <- test.cov.g$gibbs.switcheroo (test.cov.g.gibbs)

test.cov.g.gibbs.unwind <- list.output.to.matrices (test.cov.g.gibbs)
test.cov.g.gibbs.value <- test.cov.g$gibbs.value(test.cov.g.gibbs)

plot(test.cov.g.gibbs.unwind$log.lik, main="Log-likelihood")
plot(test.cov.g.gibbs.unwind$COVout.coef.cov[1,], main=paste("Coefficient 1", test.cov.g.pieces[[3]]$coef.cov[1])); abline(h=test.cov.g.pieces[[3]]$coef.cov[1], lwd=3, col=2)
color.range <- range(c(test.cov.g.value, apply(test.cov.g.gibbs.value, 1, mean)))
netplot(test.cov.g$edge.list, test.cov.g.value, colvalues=20, main="Oracle values", extremes=color.range)
netplot(test.cov.g$edge.list, apply(test.cov.g.gibbs.value, 1, mean), colvalues=20, main="Fitted values", extremes=color.range)
```

Binary within CID:
```{r}
test.cov.b <- CID.generate (100, components=list(COV(covariates=matrix(rbinom(covs*n.nodes*(n.nodes-1)/2, 1, 0.5), ncol=3), coef.cov=1:covs)), intercept=-3, residual.variance=2, generate=TRUE)
test.cov.b.pieces <- test.cov.b$pieces()
test.cov.b.value <- test.cov.b$value()

test.cov.b.gibbs <- test.cov.b$gibbs.full(draws=1000, report=100, burnin=1000, make.random.start=TRUE)
test.cov.b.gibbs.unwind <- list.output.to.matrices (test.cov.b.gibbs)
test.cov.b.gibbs.value <- test.cov.g$gibbs.value(test.cov.b.gibbs)

plot(test.cov.b.gibbs.unwind$log.lik, main="Log-likelihood")
plot(test.cov.b.gibbs.unwind$COVout.coef.cov[1,], main=paste("Coefficient 1", test.cov.b.pieces[[3]]$coef.cov[1])); abline(h=test.cov.b.pieces[[3]]$coef.cov[1], lwd=3, col=2)
color.range <- range(c(test.cov.b.value, apply(test.cov.b.gibbs.value, 1, mean)))
netplot(test.cov.b$edge.list, test.cov.b.value, colvalues=20, main="Oracle values", extremes=color.range)
netplot(test.cov.b$edge.list, apply(test.cov.b.gibbs.value, 1, mean), colvalues=20, main="Fitted values", extremes=color.range)

netplot(test.cov.b$edge.list, 1*(test.cov.b.value>0), colvalues=20, main="Oracle values")
netplot(test.cov.b$edge.list, 1*(1*(apply(test.cov.b.gibbs.value, 1, mean)>0) == 1*(test.cov.b.value>0)), colvalues=20, main="Fitted values")
plot(jitter(test.cov.b.value), jitter(apply(test.cov.b.gibbs.value, 1, mean)))

```

