Checking the CIDnetworks Suite: LSM
========================================================

A.C. Thomas, November 21

First, I check each of the subcomponents for their correct use within the entire structure. `r library(CIDnetworks)`


Basic Structure
---------------

First: checking the intercept-only model (Gilbert model).

Normal data:

```{r}
basic <- CID.generate (100, intercept=1, residual.variance=2, generate=TRUE)
basic.pieces <- basic$pieces()
basic.gibbs <- basic$gibbs.full(draws=1000, report=1000, make.random.start=TRUE)
basic.gibbs.unwind <- list.output.to.matrices (basic.gibbs)
basic.gibbs.value <- basic$gibbs.value(basic.gibbs)
par(mfrow=c(1,3))
plot(basic.gibbs.unwind$intercept, main="Intercept"); abline(h=basic.pieces$intercept, col=2, lwd=3)
plot(basic.gibbs.unwind$residual.variance, main="Residual Variance"); abline(h=basic.pieces$residual.variance, col=2, lwd=3)
plot(basic.gibbs.unwind$log.likelihood, main="Log Likelihood")
```

Binary data:

```{r}
basic <- CID.generate (100, intercept=1, generate=TRUE, class.outcome="binary")
basic.pieces <- basic$pieces()
basic.gibbs <- basic$gibbs.full(draws=1000, report=1000, make.random.start=TRUE)
basic.gibbs.unwind <- list.output.to.matrices (basic.gibbs)
par(mfrow=c(1,3))
plot(basic.gibbs.unwind$intercept, main="Intercept"); abline(h=basic.pieces$intercept, col=2, lwd=3)
plot(basic.gibbs.unwind$residual.variance, main="Residual Variance"); abline(h=basic.pieces$residual.variance, col=2, lwd=3)
plot(basic.gibbs.unwind$log.likelihood, main="Log Likelihood")
```


Latent Space Model:
-------------------

Component alone, negative inflation factor (standard LSM).

```{r}
test.lsm <- LSM(n.nodes=100, mult.factor=-1, generate=TRUE)
test.lsm.pieces <- test.lsm$pieces()
test.lsm.value <- test.lsm$value()

test.lsm.gibbs <- test.lsm$gibbs.full(draws=500, report=100, burnin=200, thin=2, make.random.start=TRUE)
test.lsm.gibbs.unlist <- list.output.to.matrices (test.lsm.gibbs)

test.lsm.gibbs.value <- test.lsm$gibbs.value(test.lsm.gibbs)
par(mfrow=c(2,2))
plot(test.lsm.gibbs.unlist$log.lik, main="Log-likelihood")
plot(test.lsm.gibbs.unlist$mult.factor, main=paste("Multiplication Factor", test.lsm.pieces$mult.factor)); abline(h=test.lsm.pieces$mult.factor, lwd=3, col=2)
netplot(test.lsm$edge.list, test.lsm.value, colvalues=20, main="Oracle values")
netplot(test.lsm$edge.list, apply(test.lsm.gibbs.value, 1, mean), colvalues=20, main="Fitted values")
```

Component alone, positive inflation factor (standard LSM).

```{r}
test.lsm <- LSM(n.nodes=100, mult.factor=2, generate=TRUE)
test.lsm.pieces <- test.lsm$pieces()
test.lsm.value <- test.lsm$value()

test.lsm.gibbs <- test.lsm$gibbs.full(draws=500, report=100, burnin=200, thin=2, make.random.start=TRUE)
test.lsm.gibbs.unlist <- list.output.to.matrices (test.lsm.gibbs)

test.lsm.gibbs.value <- test.lsm$gibbs.value(test.lsm.gibbs)
par(mfrow=c(2,2))
plot(test.lsm.gibbs.unlist$log.lik, main="Log-likelihood")
plot(test.lsm.gibbs.unlist$mult.factor, main=paste("Multiplication Factor", test.lsm.pieces$mult.factor)); abline(h=test.lsm.pieces$mult.factor, lwd=3, col=2)
netplot(test.lsm$edge.list, test.lsm.value, colvalues=20, main="Oracle values")
netplot(test.lsm$edge.list, apply(test.lsm.gibbs.value, 1, mean), colvalues=20, main="Fitted values")
```


Gaussian within CID:

```{r}
test.lsm.g <- CID.generate (100, components=list(LSM(2, mult.factor=-1)), intercept=1, residual.variance=2, generate=TRUE)
test.lsm.g.pieces <- test.lsm.g$pieces()
test.lsm.g.value <- test.lsm.g$value()

test.lsm.g.gibbs <- test.lsm.g$gibbs.full(draws=300, report=100, burnin=300, make.random.start=TRUE)
test.lsm.g.gibbs.unwind <- list.output.to.matrices (test.lsm.g.gibbs)
test.lsm.g.gibbs.value <- test.lsm.g$gibbs.value(test.lsm.g.gibbs)

par(mfrow=c(3,2))
plot(test.lsm.g.gibbs.unwind$intercept, main="Intercept"); abline(h=test.lsm.g.pieces$intercept, col=2, lwd=3)
plot(test.lsm.g.gibbs.unwind$LSMout.mult.factor, main=paste("Multiplication Factor", test.lsm.g.pieces[[3]]$mult.factor)); abline(h=test.lsm.g.pieces[[3]]$mult.factor, col=2, lwd=3)

plot(test.lsm.g.gibbs.unwind$residual.variance, main="Residual Variance"); abline(h=test.lsm.g.pieces$residual.variance, col=2, lwd=3)
plot(test.lsm.g.gibbs.unwind$log.likelihood, main="Log Likelihood")

color.range <- range(c(test.lsm.g.value, apply(test.lsm.g.gibbs.value, 1, mean)))
netplot(test.lsm.g$edge.list, test.lsm.g.value, colvalues=20, main="Oracle values", extremes=color.range)
netplot(test.lsm.g$edge.list, apply(test.lsm.g.gibbs.value, 1, mean), colvalues=20, main="Fitted values", extremes=color.range)
```


Binary within CID:

```{r}
test.lsm.b <- CID.generate (100, components=list(LSM(2, mult.factor=-1)), intercept=0, generate=TRUE, class.outcome="binary")
test.lsm.b.pieces <- test.lsm.b$pieces()
test.lsm.b.value <- test.lsm.b$value()

test.lsm.b.gibbs <- test.lsm.b$gibbs.full(draws=1000, report=100, burnin=500, make.random.start=TRUE)
test.lsm.b.gibbs.unwind <- list.output.to.matrices (test.lsm.b.gibbs)
test.lsm.b.gibbs.value <- test.lsm.g$gibbs.value(test.lsm.b.gibbs)

par(mfrow=c(3,2))
plot(test.lsm.b.gibbs.unwind$intercept, main=paste("Intercept", test.lsm.b.pieces$intercept)); abline(h=test.lsm.b.pieces$intercept, col=2, lwd=3)
plot(test.lsm.b.gibbs.unwind$LSMout.mult.factor, main=paste("Multiplication Factor", test.lsm.b.pieces[[3]]$mult.factor)); abline(h=test.lsm.b.pieces[[3]]$mult.factor, col=2, lwd=3)

plot(test.lsm.b.gibbs.unwind$residual.variance, main="Residual Variance"); abline(h=test.lsm.b.pieces$residual.variance, col=2, lwd=3)
plot(test.lsm.b.gibbs.unwind$log.likelihood, main="Log Likelihood")

color.range <- range(c(test.lsm.b.value, apply(test.lsm.b.gibbs.value, 1, mean)))
netplot(test.lsm.b$edge.list, test.lsm.b.value, colvalues=20, main="Oracle values", extremes=color.range)
netplot(test.lsm.b$edge.list, apply(test.lsm.b.gibbs.value, 1, mean), colvalues=20, main="Fitted values", extremes=color.range)
```


